### ISSUE TITLE
函数缺失

### ISSUE THREAD

**Issue by Sisyphus-pandapia** [thinszx/WiFi-CSI-gait-recognition#2]
请问已开源的代码中是否缺失了函数findvalleys？运行extract_file_features时发现，您提供的功能函数中缺失这一函数，因此无法提取特征。

**Comment by thinszx** [comment]
感谢关注本项目，在该项目中波峰/波谷的大部分检测函数，包括`findvalleys`，均调用自[iPeak](https://www.mathworks.com/matlabcentral/fileexchange/23850-ipeak)，这是马里兰大学一本信号处理书的附属程序，可以通过以下任意一种方式获取：
1. 在MATLAB App选项栏中的 `获取更多App` 栏中搜索 `Peak finding and measurement, 2019` ，安装App获取这些函数
2. 通过[MATLAB File Exchange](https://www.mathworks.com/matlabcentral/fileexchange/23850-ipeak)下载程序集，然后把程序集路径添加到MATLAB的搜寻路径中
3. 参考[该书的官方网站](https://terpconnect.umd.edu/~toh/spectrum/)了解这个程序集

为了方便使用我已经把该项目集放在 `tools` 文件夹下，请重新从GitHub拉取项目获取文件，如果该问题和第一个issue并不属于同一问题，可以继续向我提问
