### ISSUE TITLE
为什么只能处理的路径-接收器对为1-R3和3-R6，且重复次数应为偶数次的文件呢？

### ISSUE THREAD

**Issue by dzdgd** [thinszx/WiFi-CSI-gait-recognition#4]
必须得穿过接受和发送器的视距吗？可以详细的解释一下吗，或者提供一下相应的文献资料
![image](https://github.com/thinszx/WiFi-CSI-gait-recognition/assets/42370296/ddef5aab-255c-4ef8-9098-1ba5c89600b5)

**Comment by thinszx** [comment]
你好，之所以有这样的限制是因为本项目的步态特征提取过程是依赖于人行走时身体引起的多普勒频移特征的。而目前对CSI信号传播的路径经常被建模为一个椭圆场，椭圆的焦点分别为两个接收设备，在这个场中人体相关运动能够引起CSI幅值最大变化的路径就是椭圆两个焦点的中垂线，因为这个时候信号传播方向与人的运动方向完全垂直，可以类比一下电磁场中当小球沿电磁线垂直方向运动时受作用力最大，是类似的道理。

做这个项目的时候因为只是当毕设做，所以没考虑特别复杂的情况，在特征提取（训练）过程中因为只使用了你提到的这两个路径，而且没有引入人运动方向相关的因子，所以会有这样的限制。但目前已经有很多工作将人的运动路径考虑在了步态识别过程中，例如张大庆教授团队做过一个工作，先检测了人的运动方向，然后进行了类似“频谱搬移”的工作，将时频谱修正到了接近沿椭圆焦点中垂线的方向行走时捕获到的频谱，然后再进行识别，这篇论文的名字我不太记得了。另外清华的杨峥教授也做过类似的方向无关特征提取工作，可以参考一下他们的Widar 3.0。

我提到的CSI及其建模相关的参考文献也可以参见北大张大庆教授团队的工作，例如Niu K, Wang X, Zhang F, et al. Rethinking Doppler effect for accurate velocity estimation with commodity WiFi devices[J]. IEEE Journal on Selected Areas in Communications, 2022, 40(7): 2164-2178.
